const data = {
    products: [
        {
            name: 'Nike Trainer',
            slug: 'nike-trainer',
            category: 'Pants',
            image: '/images/image1.jpeg',
            price: 110,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            name: 'Nike Jordan',
            slug: 'nike-jordan',
            category: 'Pants',
            image: '/images/image2.jpeg',
            price: 180,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            name: 'Nike Jordan Low',
            slug: 'nike-jordan-low',
            category: 'Pants',
            image: '/images/image3.jpeg',
            price: 100,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            name: 'Nike Jordan Zoom',
            slug: 'nike-jordan-zoom',
            category: 'Pants',
            image: '/images/image4.jpeg',
            price: 190,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
    ],
};
export default data;